version: '3.5'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ${APP_NAME}_backend
    restart: always
    depends_on:
      - database
    env_file:
      - .env.app
    ports:
      - ${BACKEND_PORT}:80
      - ${BACKEND_PORT_SSL}:443

  database:
    image: mysql
    container_name: ${APP_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_EXPOSE_PORT}:3306
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
    name: ${APP_NAME}_mysql

networks:
  default:
    name: ${APP_NAME}_network
    driver: bridge
